remote_theme: eliottvincent/bay
title: Homepage of Jean Teyssandier
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my research website!
baseurl: "" # the subpath of the site
url: "https://jeanteyssandier.github.io" # the base hostname & protocol for the site
og_image: mode1_lin_lr.png
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publications

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: jean (dot) teyssandier (at) unamur (dot) be
      link: mailto:jean.teyssandier@unamur.be
  follow:
    - name: GitHub
      link: http://github.com/jeanteyssandier

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
